spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/strydal
    username: strydal
    password: strydal
    generate-ddl: ${CREATE_DB:false}

  jackson:
    deserialization:
      adjust_dates_to_context_time_zone: false

  security:
    jwt_secret_key: TopSecretKey

logging:
  level:
    org.springframework.web.servlet: INFO
    Exposed: DEBUG

app:
  appName: "strydal-backend"